AWSTemplateFormatVersion: '2010-09-09'
Description: 'Serverless VPC with single AZ (Minimal cost)'

Parameters:
  ProjectName:
    Type: String
    Default: dev-gassyuku
    Description: Project name for tagging

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC

  PrivateSubnet1Cidr:
    Type: String
    Default: 10.0.10.0/24

Resources:
  # VPC 本体
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-vpc

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet1Cidr
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-private-1

  # --- ルートテーブル ---
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-private-rt

  # ルートテーブルの関連付け
  PrivateSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  # --- VPC Endpoints ---
  # S3 Gateway Endpoint (無料)
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !Ref VPC
      RouteTableIds:
        - !Ref PrivateRouteTable
      VpcEndpointType: Gateway
      #  S3 Endpoint ポリシーで同じAWSアカウント&リージョンへのアクセスへ限定する（オプション）
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::*"
            Condition:
              StringEquals:
                s3:ResourceAccount: !Sub "${AWS::AccountId}"

  # --- セキュリティグループ ---

  # Lambda 用
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: !Ref VPC
      # アウトバウンドはデフォルトで全許可
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-lambda-sg

Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: !Sub ${ProjectName}-VPCID

  PrivateSubnets:
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${ProjectName}-PrivateSubnets

  LambdaSecurityGroupId:
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: !Sub ${ProjectName}-LambdaSG
